# Netlify配置文件

[build]
  # 构建输出目录
  publish = "."
  # 构建命令（静态站点无需构建）
  command = "echo 'No build required for static site'"

[functions]
  # Serverless函数目录
  directory = "netlify/functions"

[[redirects]]
  # API路由重定向
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 环境变量（在Netlify控制台中设置）
# CLOUDINARY_CLOUD_NAME=你的云名称
# CLOUDINARY_API_KEY=你的API密钥  
# CLOUDINARY_API_SECRET=你的API密钥

# 表单处理
[build.environment]
  NODE_VERSION = "18"
